[tool.poetry]
name = "Vectors_Matrix"
version = "0.1.0"
description = "Vectors_Matrix"
authors = ["Siia <your@email.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
